import { NextRequest,NextResponse } from 'next/server';
export const runtime='nodejs';
export async function POST(req:NextRequest){try{
 const {posts}=await req.json(); const published=Array.isArray(posts)?posts.filter(p=>p.status==='published'&&p.metrics&&p.postId).slice(0,30):[];
 if(published.length<3)return NextResponse.json({error:'Publish and ingest metrics for all three channels first.'},{status:400});
 const key=process.env.GEMINI_API_KEY;if(!key)return NextResponse.json({error:'AI report unavailable: GEMINI_API_KEY is not configured.'},{status:503});
 const facts=published.map(p=>({postId:String(p.postId).slice(0,40),channel:p.channel,headline:String(p.headline).slice(0,80),impressions:Number(p.metrics.impressions)||0,engagements:Number(p.metrics.engagements)||0,clicks:Number(p.metrics.clicks)||0,engagementRate:+((Number(p.metrics.engagements)||0)/Math.max(1,Number(p.metrics.impressions))*100).toFixed(2),ctr:+((Number(p.metrics.clicks)||0)/Math.max(1,Number(p.metrics.impressions))*100).toFixed(2)}));
 const prompt=`You are a streaming content insights analyst. Write concise weekly campaign analysis using ONLY the provided mock/simulated metrics (never claim real platform analytics). Compare same campaign across platforms using normalized engagement and click-through rates, not raw totals. Every numeric claim MUST cite exact post IDs in square brackets, e.g. [IG-123]. State one concrete hypothesis for next brief and the limitation that these are simulated. Output JSON only: {"summary":"3 sentences with post ID citations","nextBrief":"specific action for next campaign, one sentence","winningChannel":"Instagram|YouTube|X"}. Facts: ${JSON.stringify(facts)}`;
 const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${encodeURIComponent(key)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{responseMimeType:'application/json',temperature:.3}}),cache:'no-store',signal:AbortSignal.timeout(28000)});const data=await r.json();if(!r.ok)return NextResponse.json({error:`Gemini report failed (${r.status})`},{status:502});const parsed=JSON.parse(data.candidates?.[0]?.content?.parts?.map((p:{text:string})=>p.text).join('')||'{}');let summary=String(parsed.summary||'').slice(0,1800);if(!published.some(p=>summary.includes(`[${p.postId}]`)))return NextResponse.json({error:'AI report lacked post ID citations. Retry.'},{status:502});return NextResponse.json({summary,nextBrief:String(parsed.nextBrief||'').slice(0,320),winningChannel:parsed.winningChannel,model:'Gemini 2.5 Flash',sourcePostIds:facts.map(x=>x.postId)});
}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Report failed'},{status:500})}}
