'use client';
import {FormEvent,useState} from 'react';
import Link from 'next/link';
import {ArrowLeft,ArrowUpRight,Eye,EyeOff,LockKeyhole,Mail,ShieldCheck,Sparkles} from 'lucide-react';
import {supabase} from './client';
export default function AuthForm({mode}:{mode:'login'|'signup'}){
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[visible,setVisible]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 async function submit(e:FormEvent){e.preventDefault();setError('');setMessage('');const sb=supabase();if(!sb){setError('Sign-in is being configured. The public demo remains available.');return}setBusy(true);
 try{if(mode==='signup'){const {data,error}=await sb.auth.signUp({email,password,options:{emailRedirectTo:`${location.origin}/studio`}});if(error)throw error;if(data.session)location.assign('/studio');else setMessage('Check your email for a confirmation link, then come back to sign in.')}else{const {error}=await sb.auth.signInWithPassword({email,password});if(error)throw error;location.assign('/studio')}}catch(e){setError(e instanceof Error?e.message:'Could not continue. Please try again.')}finally{setBusy(false)}}
 return <main className="auth-layout"><div className="auth-art"><Link href="/" className="auth-back"><ArrowLeft size={16}/> Back to FRAME</Link><div className="auth-orbit"><i/><i/><i/><span>f.</span></div><div className="auth-art-copy"><span className="kicker">ONE BRIEF. THREE WORLDS.</span><h1>Make every<br/><em>frame count.</em></h1><p>Built for stories that deserve to travel further.</p></div></div><div className="auth-form-side"><div className="auth-form-wrap"><div className="auth-mark"><span>f.</span> frame <small>CONTENT INTELLIGENCE</small></div><span className="kicker">{mode==='signup'?'CREATE YOUR SPACE':'WELCOME BACK'}</span><h2>{mode==='signup'?'Start something worth watching.':'Pick up where the story left off.'}</h2><p className="auth-sub">{mode==='signup'?'Create an account to access the studio. Campaign drafts stay in this browser.':'Sign in to continue to the creative studio.'}</p><form onSubmit={submit}><label>Email address<div className="auth-input"><Mail size={18}/><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" required autoComplete="email"/></div></label><label>Password<div className="auth-input"><LockKeyhole size={18}/><input type={visible?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} placeholder={mode==='signup'?'At least 6 characters':'Enter your password'} minLength={6} required autoComplete={mode==='signup'?'new-password':'current-password'}/><button type="button" onClick={()=>setVisible(!visible)} aria-label={visible?'Hide password':'Show password'}>{visible?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></label>{error&&<p className="auth-error" role="alert">{error}</p>}{message&&<p className="auth-success" role="status">{message}</p>}<button className="auth-submit" disabled={busy}>{busy?'One moment...':mode==='signup'?'Create account':'Sign in'}<ArrowUpRight size={18}/></button></form><p className="auth-switch">{mode==='signup'?'Already have an account?':'New to frame?'} <Link href={mode==='signup'?'/login':'/signup'}>{mode==='signup'?'Sign in':'Create an account'}</Link></p><div className="auth-demo"><ShieldCheck size={18}/><span>Judging the prototype? No account needed.</span><Link href="/studio">Explore the demo <ArrowUpRight size={14}/></Link></div></div><footer className="auth-footer">Independent hackathon prototype · <a href="https://anuragroy.tech" target="_blank" rel="noopener noreferrer">Made by Anurag Roy</a></footer></div></main>
}
