export type Channel='Instagram'|'YouTube'|'X';
export type Status='draft'|'approved'|'scheduled'|'published';
export type Post={id:string;channel:Channel;headline:string;bengali:string;english:string;caption:string;visual:string;palette:string[];motif:string;ratio:string;status:Status;createdAt:string;scheduledAt?:string;postId?:string;metrics?:{impressions:number;engagements:number;clicks:number}};
export const specs:Record<Channel,{ratio:string;limit:number;maxBytes:number;label:string}>={Instagram:{ratio:'4:5',limit:2200,maxBytes:2_000_000,label:'Portrait 4:5'},YouTube:{ratio:'16:9',limit:5000,maxBytes:2_000_000,label:'Widescreen 16:9'},X:{ratio:'1:1',limit:280,maxBytes:2_000_000,label:'Square 1:1'}};
export function posterSvg(p:Post):string{
 const [a,b,c]=p.palette;const dims=p.channel==='Instagram'?[800,1000]:p.channel==='YouTube'?[1280,720]:[900,900];const [w,h]=dims;
 const esc=(s:string)=>s.replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[x]||x));
 const id=p.id.replace(/[^a-z0-9]/gi,'').slice(0,12);const motif=p.motif;
 const symbols:Record<string,string>={moon:`<circle cx="${w*.69}" cy="${h*.34}" r="${w*.2}" fill="url(#halo)"/><circle cx="${w*.69}" cy="${h*.34}" r="${w*.135}" fill="${c}" opacity=".9"/>`,rain:`<g stroke="${c}" opacity=".55" stroke-width="3">${Array.from({length:22},(_,i)=>`<path d="M${i*w/19-30} -30 l-${w*.18} ${h*.9}"/>`).join('')}</g><circle cx="${w*.63}" cy="${h*.4}" r="${w*.17}" fill="${a}" opacity=".44"/>`,city:`<path d="M0 ${h*.73} V${h*.38}h${w*.17}v${h*.14}h${w*.1}V${h*.27}h${w*.17}v${h*.22}h${w*.12}v-${h*.14}h${w*.14}v${h*.2}h${w*.2}V${h*.73}Z" fill="${c}" opacity=".24"/><circle cx="${w*.7}" cy="${h*.28}" r="${w*.15}" fill="${a}" opacity=".6"/>`,letter:`<g transform="translate(${w*.38} ${h*.25}) rotate(-13)"><rect width="${w*.48}" height="${h*.42}" rx="9" fill="${c}" opacity=".86"/><path d="M0 0 L${w*.24} ${h*.21} L${w*.48} 0" fill="none" stroke="${a}" stroke-width="5"/></g>`,train:`<path d="M${w*.16} ${h*.25}L${w*.82} ${h*.25} L${w*.73} ${h*.78} L${w*.22} ${h*.78}Z" fill="${c}" opacity=".24"/><path d="M${w*.3} ${h*.8}L${w*.06} ${h}M${w*.7} ${h*.8}L${w*.94} ${h}" stroke="${a}" stroke-width="10"/>`,window:`<rect x="${w*.26}" y="${h*.15}" width="${w*.53}" height="${h*.59}" rx="${w*.025}" fill="${c}" opacity=".37"/><path d="M${w*.525} ${h*.15}v${h*.59} M${w*.26} ${h*.45}h${w*.53}" stroke="${a}" stroke-width="11"/>`};
 const headline=esc(p.headline).slice(0,72);return `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}" role="img" aria-label="${headline} illustrated concept"><defs><linearGradient id="bg${id}" x1="0" y1="0" x2="1" y2="1"><stop stop-color="${b}"/><stop offset="1" stop-color="${a}"/></linearGradient><radialGradient id="halo"><stop stop-color="${c}" stop-opacity=".8"/><stop offset="1" stop-color="${c}" stop-opacity="0"/></radialGradient><filter id="grain"><feTurbulence type="fractalNoise" baseFrequency=".68" numOctaves="3" stitchTiles="stitch"/><feColorMatrix type="saturate" values="0"/><feComponentTransfer><feFuncA type="linear" slope=".1"/></feComponentTransfer></filter></defs><rect width="${w}" height="${h}" fill="url(#bg${id})"/><g>${symbols[motif]||symbols.moon}</g><rect width="${w}" height="${h}" filter="url(#grain)" opacity=".45"/><rect x="${w*.065}" y="${h*.065}" width="${w*.87}" height="${h*.87}" rx="8" fill="none" stroke="${c}" stroke-opacity=".46" stroke-width="2"/><text x="${w*.09}" y="${h*.13}" font-family="Arial,sans-serif" font-size="${w*.02}" letter-spacing="${w*.008}" fill="${c}">FRAME / CREATIVE STUDY</text><foreignObject x="${w*.09}" y="${h*.67}" width="${w*.82}" height="${h*.2}"><div xmlns="http://www.w3.org/1999/xhtml" style="font:bold ${w*.075}px/1.05 Georgia,serif;color:${c};overflow-wrap:break-word;max-height:100%;overflow:hidden">${headline}</div></foreignObject><text x="${w*.09}" y="${h*.92}" font-family="Arial,sans-serif" font-size="${w*.018}" letter-spacing="${w*.006}" fill="${c}">A CONCEPT FOR ${esc(p.channel.toUpperCase())}</text></svg>`;
}
export function validatePost(p:Post,asset?:{mime:string;bytes:number;width:number;height:number}){
 const errors:string[]=[];const s=specs[p.channel];if(!s)errors.push('Unknown platform');if(p.caption.length>s.limit)errors.push(`Caption is ${p.caption.length} characters; ${p.channel} max is ${s.limit}.`);
 if(!p.caption.trim())errors.push('Caption is empty.');if(!p.bengali.trim()||!p.english.trim())errors.push('Bengali and English copy are both required.');
 const svg=posterSvg(p);const bytes=new TextEncoder().encode(svg).length; const [w,h]=p.channel==='Instagram'?[800,1000]:p.channel==='YouTube'?[1280,720]:[900,900];
 const actual=asset||{mime:'image/svg+xml',bytes,width:w,height:h};if(!['image/svg+xml','image/png','image/jpeg','image/webp'].includes(actual.mime))errors.push('Unsupported asset MIME type.');if(actual.bytes>s.maxBytes)errors.push(`Creative exceeds ${s.maxBytes/1e6} MB limit.`);
 const [rw,rh]=s.ratio.split(':').map(Number); if(Math.abs(actual.width/actual.height-rw/rh)>.015)errors.push(`Wrong aspect ratio. Expected ${s.ratio}, got ${actual.width}×${actual.height}.`);
 if(actual.width<500||actual.height<500)errors.push('Creative must be at least 500 px on both sides.');return {valid:errors.length===0,errors,asset:{...actual,ratio:s.ratio}};
}
export function metricsFor(p:Post){let hash=[...p.id].reduce((a,c)=>a*31+c.charCodeAt(0),7)>>>0;let impressions=1200+hash%5300;let rate=(p.channel==='Instagram'?.055:p.channel==='YouTube'?.038:.025)+((hash%9)-4)*.002;let engagements=Math.round(impressions*rate);return {impressions,engagements,clicks:Math.round(engagements*(p.channel==='YouTube'?.22:.14))}}
