'use client';
import Link from 'next/link';
import {ArrowUpRight,ArrowRight,Play,Instagram,Film,BarChart3,CheckCircle2,ShieldCheck,Sparkles,MousePointer2,Menu,X} from 'lucide-react';
import {useState} from 'react';
const steps=[{n:'01',label:'A single spark',description:'Give the engine a story, audience and emotional hook. Start with the sample brief if you want to see it move.'},{n:'02',label:'Three distinct worlds',description:'See a platform-native visual concept and Bengali and English copy for Instagram, YouTube and X.'},{n:'03',label:'Your call, always',description:'Review and edit. Nothing enters the queue until you approve each piece. The adapter rejects invalid assets.'},{n:'04',label:'Learn what landed',description:'Simulate a release, compare normalized metrics and carry a cited AI insight into the next brief.'}];
export default function Landing(){const [active,setActive]=useState(0),[menu,setMenu]=useState(false);return <div className="landing"><header className="landing-nav"><Link className="landing-brand" href="/"><span>f.</span><strong>frame</strong><small>CONTENT INTELLIGENCE</small></Link><nav className={menu?'open':''}><a href="#experience" onClick={()=>setMenu(false)}>The experience</a><Link href="/guide" onClick={()=>setMenu(false)}>How it works</Link><Link href="/login" onClick={()=>setMenu(false)}>Sign in</Link><Link href="/signup" className="nav-cta" onClick={()=>setMenu(false)}>Get started <ArrowUpRight size={15}/></Link></nav><button className="landing-menu" onClick={()=>setMenu(!menu)} aria-label={menu?'Close menu':'Open menu'}>{menu?<X/>:<Menu/>}</button></header>
<main><section className="landing-hero"><div className="landing-grid" aria-hidden="true"/><div className="landing-orb" aria-hidden="true"><div className="landing-orb-a"/><div className="landing-orb-b"/><div className="landing-orb-c"/><div className="landing-orb-ring one"/><div className="landing-orb-ring two"/><span className="orb-tick tick-one">IDEA / 001</span><span className="orb-tick tick-two">THE NEXT FRAME</span></div><div className="landing-hero-copy"><div className="landing-eyebrow"><span className="landing-star">✦</span> THE CREATIVE ENGINE FOR STORIES IN MOTION <span className="landing-eyebrow-line"/></div><h1>One story.<br/><em>Everywhere it matters.</em></h1><p>Turn a single spark into platform-native campaigns. Make the call. Watch the signal. Come back sharper.</p><div className="landing-actions"><Link href="/studio" className="landing-primary">Enter the studio <ArrowUpRight size={19}/></Link><Link href="/guide" className="landing-secondary"><Play size={16}/> See how it works</Link></div><div className="landing-hero-note"><span><i/> AI ENGINE ONLINE</span><span>3 CHANNELS / ONE CREATIVE LOOP</span></div></div><div className="landing-vertical">FRAME / BUILT FOR WHAT COMES NEXT · 2026</div></section>
<section className="landing-strip" aria-label="Workflow"><span>01 / IMAGINE</span><i/><span>02 / MAKE</span><i/><span>03 / DECIDE</span><i/><span>04 / LEARN</span></section>
<section className="landing-intro" id="experience"><div><span className="kicker">A DIFFERENT KIND OF CREATIVE WORKFLOW</span><h2>Not a content factory.<br/><em>A sharper instinct.</em></h2></div><p>Great campaigns do not start with a crop. They start with a feeling. Frame gives each platform its own voice, keeps people in control and turns even a simulated release into a better next decision.</p></section>
<section className="landing-feature"><div className="landing-feature-art"><div className="feature-glow"/><div className="feature-card feature-main"><div><span>FRAME / CREATIVE STUDY</span><span>01 / 03</span></div><div className="feature-poster"><div className="feature-letter">✉</div><strong>শেষ চিঠি</strong><small>A STORY HIDING IN PLAIN SIGHT</small></div><footer><Instagram size={16}/> INSTAGRAM <span>4:5</span></footer></div><div className="feature-card feature-mini mini-top"><Film size={18}/><span>YOUTUBE</span><b>16:9</b></div><div className="feature-card feature-mini mini-bottom"><span>𝕏</span><span>X</span><b>1:1</b></div></div><div className="landing-feature-copy"><span className="kicker">01 / THE WORK</span><h2>One brief.<br/><em>Three new angles.</em></h2><p>Generate original art direction and channel-aware Bengali and English copy. Instagram gets emotion. YouTube gets intrigue. X gets to the point.</p><ul><li><CheckCircle2 size={17}/> Distinct concepts, not three crops</li><li><CheckCircle2 size={17}/> Human review before scheduling</li><li><CheckCircle2 size={17}/> Downloadable SVG creative</li></ul><Link href="/studio">Open the studio <ArrowUpRight size={17}/></Link></div></section>
<section className="landing-process"><div className="process-title"><span className="kicker">THE FLOW, WITHOUT THE FRICTION</span><h2>Every move has a reason<span>.</span></h2><p>Tap a step to see how the idea becomes a decision.</p></div><div className="process-interactive"><div className="process-list">{steps.map((s,i)=><button key={s.n} className={active===i?'active':''} onClick={()=>setActive(i)} aria-expanded={active===i}><span>{s.n}</span><strong>{s.label}</strong><ArrowUpRight size={17}/></button>)}</div><div className="process-detail" key={active}><div className="process-detail-index">{steps[active].n} / 04</div><span className="process-detail-icon">{active===0?<Sparkles/>:active===1?<Film/>:active===2?<ShieldCheck/>:<BarChart3/>}</span><h3>{steps[active].label}</h3><p>{steps[active].description}</p><Link href="/guide">Walk through the guide <ArrowRight size={16}/></Link></div></div></section>
<section className="landing-honesty"><div><BarChart3 size={24}/><span className="kicker">THE FEEDBACK LOOP</span><h2>Better next time<br/>is the whole point.</h2></div><p>Compare normalized engagement and clicks, read a weekly AI memo with exact post IDs, then carry one clear hypothesis into the next campaign. The publisher and metrics are explicitly simulated. No social account is contacted.</p></section>
<section className="landing-end"><span className="kicker">YOUR NEXT IDEA IS WAITING</span><h2>Make them<br/><em>stop scrolling.</em></h2><div><Link href="/studio" className="landing-primary">Explore the live demo <ArrowUpRight size={19}/></Link><Link href="/signup" className="landing-secondary">Create an account <ArrowRight size={17}/></Link></div></section></main><footer className="landing-footer"><div className="landing-brand"><span>f.</span><strong>frame</strong><small>CONTENT INTELLIGENCE</small></div><p>Independent hackathon prototype. Not affiliated with hoichoi. Mock publishing and synthetic metrics.</p><div><Link href="/guide">Guide</Link><Link href="/studio">Studio</Link><a href="https://anuragroy.tech" target="_blank" rel="noopener noreferrer">Made by Anurag Roy <ArrowUpRight size={14}/></a></div></footer></div>}
