import { NextRequest, NextResponse } from 'next/server';
export const runtime = 'nodejs';
const channels = ['Instagram','YouTube','X'] as const;
const rules = {Instagram:{ratio:'4:5',limit:2200},YouTube:{ratio:'16:9',limit:5000},X:{ratio:'1:1',limit:280}};
function clean(v:unknown,n=500){return String(v||'').replace(/[<>]/g,'').slice(0,n)}
export async function POST(req:NextRequest){
 try{
  const input=await req.json(); const brief=clean(input.brief,1200); const title=clean(input.title,100); const audience=clean(input.audience,100);
  if(!title || brief.length<20) return NextResponse.json({error:'Add a title and a brief of at least 20 characters.'},{status:400});
  const key=process.env.GEMINI_API_KEY; if(!key) return NextResponse.json({error:'AI is not configured yet. Add GEMINI_API_KEY in Vercel project settings.'},{status:503});
  const context=clean(input.insight,350);
  const prompt=`You are a native Bengali and English OTT creative strategist. Generate distinctive social launch creative for fictional streaming title "${title}". Brief: ${brief}. Audience: ${audience||'Bengali-language streaming audiences'}. Previous campaign insight to act on: ${context||'none'}. Generate original Bengali and English copy directly in each language, NEVER translate one from the other. Each channel must have a DIFFERENT visual scene/concept, not the same art cropped. Instagram: emotional character-driven poster, native Bengali conversational copy with 2-4 hashtags and CTA. YouTube: cinematic wide thumbnail concept and search-friendly English title/description with CTA. X: graphic editorial square concept, sharp bilingual short copy within 280 characters. Avoid using actual hoichoi titles, real actors, brand trademarks or promising a trailer, streaming release, or film footage. CTAs should say follow for updates rather than watch a nonexistent video. Return ONLY JSON object {"rationale":"one sentence", "posts":[{"channel":"Instagram|YouTube|X","headline":"max 8 words","bengali":"native Bengali copy","english":"English copy","caption":"channel-ready bilingual caption including CTA and suitable hashtags","visual":"specific illustrative scene composition, not an image URL","palette":["#hex","#hex","#hex"],"motif":"one of moon,rain,city,letter,train,window"}]}. Exactly 3 posts, one per channel. All captions respect Instagram 2200, YouTube 5000, X 280 characters. No markdown fences.`;
  const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-lite:generateContent?key=${encodeURIComponent(key)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{responseMimeType:'application/json',temperature:.85}}),cache:'no-store',signal:AbortSignal.timeout(28000)});
  const raw=await r.json(); if(!r.ok) return NextResponse.json({error:`Gemini request failed (${r.status}). Check API key/quota.`},{status:502});
  const txt=raw.candidates?.[0]?.content?.parts?.map((p:{text?:string})=>p.text||'').join('')||''; let parsed; try{parsed=JSON.parse(txt)}catch{return NextResponse.json({error:'AI returned invalid JSON. Retry generation.'},{status:502})}
  if(!Array.isArray(parsed.posts) || parsed.posts.length!==3 || channels.some(c=>parsed.posts.filter((p:{channel:string})=>p.channel===c).length!==1)) return NextResponse.json({error:'AI response missed required channels. Retry.'},{status:502});
  const posts=channels.map(channel=>{let p=parsed.posts.find((x:{channel:string})=>x.channel===channel); let colors=(Array.isArray(p.palette)?p.palette:[]).map((x:unknown)=>/^#[0-9a-fA-F]{6}$/.test(String(x))?x:'#282037');return {id:crypto.randomUUID(),channel,headline:clean(p.headline,70),bengali:clean(p.bengali,400),english:clean(p.english,400),caption:clean(p.caption,rules[channel].limit),visual:clean(p.visual,300),palette:[colors[0]||'#E99482',colors[1]||'#1B1C30',colors[2]||'#F9E0BA'],motif:['moon','rain','city','letter','train','window'].includes(p.motif)?p.motif:'moon',ratio:rules[channel].ratio,status:'draft',createdAt:new Date().toISOString()}});
  return NextResponse.json({posts,rationale:clean(parsed.rationale,300),model:'Gemini 2.5 Flash-Lite'});
 }catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Generation failed'},{status:500})}
}
